export const divisions = {
	Barishal: 'Barishal',
	Chattogram: 'Chattogram',
	Dhaka: 'Dhaka',
	Khulna: 'Khulna',
	Mymensing: 'Mymensingh',
	Rajshahi: 'Rajshahi',
	Rangpur: 'Rangpur',
	Sylhet: 'Sylhet',
} as const

export type DIVISIONS = (typeof divisions)[keyof typeof divisions]

export const districtsByDivision: Record<DIVISIONS, string[]> = {
	[divisions.Barishal]: [
		'Barguna',
		'Barishal',
		'Bhola',
		'Jhalokati',
		'Patuakhali',
		'Pirojpur',
	],
	[divisions.Chattogram]: [
		'Bandarban',
		'Brahmanbaria',
		'Chandpur',
		'Chattogram',
		'Cumilla',
		"Cox's Bazar",
		'Feni',
		'Khagrachari',
		'Lakshmipur',
		'Noakhali',
		'Rangamati',
	],
	[divisions.Dhaka]: [
		'Dhaka',
		'Faridpur',
		'Gazipur',
		'Gopalganj',
		'Kishoreganj',
		'Madaripur',
		'Manikganj',
		'Munshiganj',
		'Narayanganj',
		'Narsingdi',
		'Rajbari',
		'Shariatpur',
		'Tangail',
	],
	[divisions.Khulna]: [
		'Bagerhat',
		'Chuadanga',
		'Jashore',
		'Jhenaidah',
		'Khulna',
		'Kushtia',
		'Magura',
		'Meherpur',
		'Narail',
		'Satkhira',
	],
	[divisions.Mymensing]: ['Jamalpur', 'Mymensingh', 'Netrokona', 'Sherpur'],
	[divisions.Rajshahi]: [
		'Bogra',
		'Joypurhat',
		'Naogaon',
		'Natore',
		'Chapainawabganj',
		'Pabna',
		'Rajshahi',
		'Sirajganj',
	],
	[divisions.Rangpur]: [
		'Dinajpur',
		'Gaibandha',
		'Kurigram',
		'Lalmonirhat',
		'Nilphamari',
		'Panchagarh',
		'Rangpur',
		'Thakurgaon',
	],
	[divisions.Sylhet]: ['Habiganj', 'Moulvibazar', 'Sunamganj', 'Sylhet'],
}

export const thanaByDistrict: Record<string, string[]> = {
	Barguna: [
		'Amtali',
		'Bamna',
		'Barguna Sadar',
		'Betagi',
		'Patharghata',
		'Taltali',
	],
	Barishal: [
		'Agailjhara',
		'Babuganj',
		'Bakerganj',
		'Banaripara',
		'Barishal Sadar',
		'Gournadi',
		'Hizla',
		'Mehendiganj',
		'Muladi',
	],
	Bhola: [
		'Bhola Sadar',
		'Burhanuddin',
		'Char Fasson',
		'Lalmohan',
		'Mohammadpur',
		'Tazumuddin',
	],
	Jhalokati: ['Jhalokati Sadar', 'Kathalia', 'Nalchity', 'Rajapur'],
	Patuakhali: [
		'Bauphal',
		'Dumki',
		'Galachipa',
		'Kalapara',
		'Mirzaganj',
		'Patuakhali Sadar',
	],
	Pirojpur: [
		'Bhandaria',
		'Kawkhali',
		'Mathbaria',
		'Nazirpur',
		'Pirojpur Sadar',
	],
	Bandarban: [
		'Alikadam',
		'Arbinda',
		'Bandarban Sadar',
		'Lama',
		'Naikhongchhari',
		'Rowangchhari',
		'Thanchi',
	],
	Brahmanbaria: [
		'Ashuganj',
		'Brahmanbaria Sadar',
		'Kasba',
		'Nasirnagar',
		'Sarail',
		'Shahbazpur',
		'Akhaura',
	],
	Chandpur: [
		'Chandpur Sadar',
		'Faridgonj',
		'Haimchar',
		'Haziganj',
		'Kachua',
		'Shahrasti',
	],
	Chattogram: [
		'Anwara',
		'Banshkhali',
		'Boalkhali',
		'Chandanaish',
		'Fatikchhari',
		'Hathazari',
		'Lohagara',
		'Mirsharai',
		'Patiya',
		'Rangunia',
		'Raozan',
		'Sandwip',
		'Satkania',
		'Sitakunda',
		'Chattogram Sadar',
	],
	Cumilla: [
		'Barura',
		'Brahmanpara',
		'Burichong',
		'Chandina',
		'Chauddagram',
		'Cumilla Adarsha Sadar',
		'Cumilla Sadar Dakshin',
		'Daudkandi',
		'Debidwar',
		'Laksam',
		'Meghna',
		'Monohargonj',
		'Muradnagar',
		'Nangalkot',
		'Titas',
	],
	"Cox's Bazar": [
		'Chakaria',
		"Cox's Bazar Sadar",
		'Kutubdia',
		'Maheshkhali',
		'Pekua',
	],
	Feni: ['Chhagalnaiya', 'Daganbhuiyan', 'Fulgazi', 'Feni Sadar', 'Parshuram'],
	Khagrachari: [
		'Dighinala',
		'Guimara',
		'Khagrachari Sadar',
		'Lakshmichhari',
		'Manikchhari',
		'Panchhari',
		'Ramgarh',
		'Rangamati',
		'Kaptai',
	],
	Lakshmipur: ['Lakshmipur Sadar', 'Raipur', 'Ramganj'],
	Noakhali: [
		'Begumganj',
		'Chatkhil',
		'Hatiya',
		'Kabirhat',
		'Noakhali Sadar',
		'Senbagh',
		'Sonaimuri',
	],
	Rangamati: [
		'Bagaichhari',
		'Barkal',
		'Kaptai',
		'Kawkhali',
		'Langadu',
		'Rangamati Sadar',
		'Rajasthali',
		'Belaichhari',
		'Juraichhari',
	],
	Dhaka: [
		'Dhamrai',
		'Dohar',
		'Keraniganj',
		'Nawabganj',
		'Savar',
		'Dhaka North City Corporation',
		'Dhaka South City Corporation',
	],
	Faridpur: [
		'Alfadanga',
		'Bhanga',
		'Boalmari',
		'Charbhadrasan',
		'Faridpur Sadar',
		'Madhukhali',
		'Nagarkanda',
		'Saltha',
	],
	Gazipur: ['Gazipur Sadar', 'Kaliakair', 'Kaliganj', 'Kapasia', 'Sreepur'],
	Gopalganj: ['Gopalganj Sadar', 'Kashiani', 'Muksudpur', 'Tungipara'],
	Kishoreganj: [
		'Austagram',
		'Bajitpur',
		'Bhairab',
		'Hossainpur',
		'Itna',
		'Katiadi',
		'Kishoreganj Sadar',
		'Kuliarchar',
		'Mithamain',
		'Nikli',
		'Pakundia',
		'Tarail',
	],
	Madaripur: ['Kalkini', 'Madaripur Sadar', 'Rajoir'],
	Manikganj: [
		'Daulatpur',
		'Ghior',
		'Harirampur',
		'Manikganj Sadar',
		'Saturia',
		'Shivalaya',
	],
	Munshiganj: [
		'Gazaria',
		'Lohajang',
		'Munshiganj Sadar',
		'Sreenagar',
		'Tongibari',
	],
	Narayanganj: [
		'Araihazar',
		'Bandar',
		'Narayanganj Sadar',
		'Rupganj',
		'Sonargaon',
	],
	Narsingdi: [
		'Belabo',
		'Monohardi',
		'Narsingdi Sadar',
		'Palash',
		'Raipura',
		'Shibpur',
	],
	Rajbari: ['Baliakandi', 'Kalukhali', 'Pangsha', 'Rajbari Sadar'],
	Shariatpur: [
		'Bhedarganj',
		'Damudya',
		'Gosairhat',
		'Shariatpur Sadar',
		'Zajira',
	],
	Tangail: [
		'Basail',
		'Bhuapur',
		'Delduar',
		'Dhanbari',
		'Gopalpur',
		'Kalihati',
		'Madhupur',
		'Mirzapur',
		'Nagarpur',
		'Sakhipur',
		'Tangail Sadar',
	],
	Bagerhat: [
		'Bagerhat Sadar',
		'Chitalmari',
		'Fakirhat',
		'Kachua',
		'Mollahat',
		'Mongla',
		'Rampal',
		'Sarankhola',
	],
	Chuadanga: ['Alamdanga', 'Chuadanga Sadar', 'Damurhuda', 'Jibannagar'],
	Jashore: [
		'Abhaynagar',
		'Bagherpara',
		'Chaugachha',
		'Jashore Sadar',
		'Keshabpur',
		'Manirampur',
		'Sharsha',
	],
	Jhenaidah: [
		'Harinakunda',
		'Jhenaidah Sadar',
		'Kaliganj',
		'Kotchandpur',
		'Maheshpur',
		'Shailkupa',
	],
	Khulna: [
		'Dumuria',
		'Dighalia',
		'Koyra',
		'Paikgachha',
		'Phultala',
		'Rupsha',
		'Terokhada',
		'Khulna Sadar',
	],
	Kushtia: ['Bheramara', 'Khoksa', 'Kumarkhali', 'Kushtia Sadar', 'Mirpur'],
	Magura: ['Magura Sadar', 'Mohammadpur', 'Shalik   ha', 'Sreepur'],
	Meherpur: ['Gangni', 'Meherpur Sadar', 'Mujibnagar'],
	Narail: ['Kalia', 'Lohagara', 'Narail Sadar'],
	Satkhira: [
		'Assasuni',
		'Debhata',
		'Kalaroa',
		'Kaliganj',
		'Satkhira Sadar',
		'Tala',
	],
	Jamalpur: [
		'Baksiganj',
		'Dewanganj',
		'Islampur',
		'Jamalpur Sadar',
		'Madarganj',
		'Melandaha',
		'Sarishabari',
	],
	Mymensingh: [
		'Bhaluka',
		'Dhobaura',
		'Fulbaria',
		'Gaffargaon',
		'Haluaghat',
		'Ishwarganj',
		'Mymensingh Sadar',
		'Muktagachha',
		'Nandail',
		'Phulpur',
	],
	Netrokona: [
		'Atpara',
		'Barhatta',
		'Durgapur',
		'Kalmakanda',
		'Kendua',
		'Madan',
		'Mohanganj',
		'Netrokona Sadar',
		'Purbadhala',
	],
	Sherpur: ['Jhenaigati', 'Nakla', 'Nalitabari', 'Sherpur Sadar', 'Sreebardi'],
	Bogra: [
		'Adamdighi',
		'Bogura Sadar',
		'Dhunat',
		'Dhupchanchia',
		'Gabtali',
		'Kahaloo',
		'Nandigram',
		'Sariakandi',
		'Shajahanpur',
		'Sherpur',
		'Sonatala',
	],
	Joypurhat: ['Akkelpur', 'Joypurhat Sadar', 'Kalai', 'Khetlal', 'Panchbibi'],
	Naogaon: [
		'Atrai',
		'Badalgachhi',
		'Dhamoirhat',
		'Manda',
		'Naogaon Sadar',
		'Niamatpur',
		'Patnitala',
		'Porsha',
		'Raninagar',
		'Sapahar',
		'Mohadebpur',
	],
	Natore: ['Bagatipara', 'Baraigram', 'Gurudaspur', 'Lalpur', 'Natore Sadar'],
	Chapainawabganj: [
		'Bholahat',
		'Gomastapur',
		'Nachole',
		'Nawabganj Sadar',
		'Shibganj',
	],
	Pabna: [
		'Atgharia',
		'Bera',
		'Bhangura',
		'Chatmohar',
		'Faridpur',
		'Ishwardi',
		'Pabna Sadar',
		'Santhia',
		'Sujanagar',
	],
	Rajshahi: [
		'Bagha',
		'Bagmara',
		'Charghat',
		'Durgapur',
		'Godagari',
		'Mohanpur',
		'Paba',
		'Puthia',
		'Tanore',
		'Rajshahi Sadar',
	],
	Sirajganj: [
		'Belkuchi',
		'Chauhali',
		'Kamarkhanda',
		'Kazipur',
		'Raiganj',
		'Shahjadpur',
		'Sirajganj Sadar',
		'Tarash',
		'Ullahpara',
	],
	Dinajpur: [
		'Birampur',
		'Biral',
		'Bochaganj',
		'Chirirbandar',
		'Dinajpur Sadar',
		'Ghoraghat',
		'Hakimpur',
		'Kaharole',
		'Khansama',
		'Nawabganj',
		'Parbatipur',
		'Phulbari',
	],
	Gaibandha: [
		'Gaibandha Sadar',
		'Gobindaganj',
		'Palashbari',
		'Phulchhari',
		'Sadullapur',
		'Sundarganj',
	],
	Kurigram: [
		'Bhurungamari',
		'Chilmari',
		'Phulbari',
		'Kurigram Sadar',
		'Nageshwari',
		'Rajarhat',
		'Ulipur',
	],
	Lalmonirhat: [
		'Aditmari',
		'Hatibandha',
		'Kaliganj',
		'Lalmonirhat Sadar',
		'Patgram',
	],
	Nilphamari: [
		'Dimla',
		'Domar',
		'Jaldhaka',
		'Kishoreganj',
		'Nilphamari Sadar',
		'Saidpur',
	],
	Panchagarh: ['Atwari', 'Boda', 'Debiganj', 'Panchagarh Sadar', 'Tetulia'],
	Rangpur: [
		'Badarganj',
		'Gangachhara',
		'Kaunia',
		'Mithapukur',
		'Pirgachha',
		'Rangpur Sadar',
		'Taraganj',
	],
	Thakurgaon: ['Baliadangi', 'Haripur', 'Ranisal', 'Thakurgaon Sadar'],
	Habiganj: [
		'Ajmiriganj',
		'Bahubal',
		'Baniachong',
		'Chunarughat',
		'Habiganj Sadar',
		'Lakhai',
		'Madhabpur',
	],
	Moulvibazar: [
		'Barlekha',
		'Kamalganj',
		'Kulaura',
		'Moulvibazar Sadar',
		'Rajnagar',
		'Sreemangal',
	],
	Sunamganj: [
		'Bishwamvarpur',
		'Chhatak',
		'Derai',
		'Dharampasha',
		'Dowarabazar',
		'Jagannathpur',
		'Jamalganj',
		'Sullah',
		'Sunamganj Sadar',
		'Tahirpur',
	],
	Sylhet: [
		'Beanibazar',
		'Bishwanath',
		'Companiganj',
		'Fenchuganj',
		'Golapganj',
		'Gowainghat',
		'Jaintiapur',
		'Kanaighat',
		'Sylhet Sadar',
		'Zakiganj',
	],
}

export const getDistrictsForDivision = (division: string): string[] => {
	if (!division) return []

	const divisionKey = Object.keys(districtsByDivision).find(
		(key) => key.toLowerCase() === division.toLowerCase(),
	)

	return divisionKey ? districtsByDivision[divisionKey as DIVISIONS] : []
}

export async function getLocations(request: Request) {
	const searchParams = new URL(request.url).searchParams
	const query = searchParams.get('query')?.toLocaleLowerCase()

	if (!query || query.length < 2) {
		return { divisions: [], districts: [] }
	}

	// Find matching divisions
	const matchingDivisions = Object.values(divisions).filter((division) =>
		division.toLocaleLowerCase().includes(query),
	)

	// Find matching districts
	const matchingDistricts = Object.entries(districtsByDivision)
		.flatMap(([division, districts]) =>
			districts
				.filter((district) => district.toLocaleLowerCase().includes(query))
				.map((district) => ({ division, district })),
		)
		.map(({ district }) => district)

	if (matchingDivisions.length > 0) {
		return {
			divisions: matchingDivisions,
			districts: matchingDistricts,
			thanas: [],
		}
	}

	const matchingThanas = Object.entries(thanaByDistrict)
		.flatMap(([district, thanas]) =>
			thanas
				.filter((thana) => thana.toLocaleLowerCase().includes(query))
				.map((thana) => ({ district, thana })),
		)
		.map(({ district, thana }) => `${thana}, ${district}`)

	return {
		divisions: matchingDivisions,
		districts: matchingDistricts,
		thanas: matchingThanas,
	}
}
